<?php
//数据库配置
define('DB_TYPE','mysql');//数据库类型
define('DB_HOST','localhost');//数据库主机
define('DB_USER','root');//数据库用户名
define('DB_PWD','');//数据库密码
define('DB_PORT',3306);//数据库端口，mysql默认是3306
define('DB_NAME','gift_appgame_com');//数据库名
define('DB_CHARSET','utf8');//数据库编码
define('DB_PREFIX','hoho_');//数据库前缀
define('DB_PCONNECT',false);//true表示使用永久连接，false表示不适用永久连接，一般不使用永久连接
?>